# Generated by Django 2.2 on 2019-05-19 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='mood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraps.Mood'),
        ),
    ]
