# Generated by Django 2.2 on 2019-05-19 02:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scraps', '0002_auto_20190518_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
