# Generated by Django 2.2 on 2019-05-19 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scraps', '0003_auto_20190518_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrap',
            options={'ordering': ('-posted',)},
        ),
        migrations.AddField(
            model_name='scrap',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scrap',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
    ]
